name: "robocompdsl test"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Images"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  make-compilation-test:
    runs-on: ubuntu-latest
    container:
      image: "robocomp/robocomp:development__dsr__latest"
      options: --user robolab

    steps:
      - run: "cd /home/robolab/robocomp/tools/cli/robocompdsl/test/ && python3 -m unittest2 discover -p 'test_*.py'"
  fail-on-image-fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: "exit 1"
